### ISSUE TITLE
在本地运行项目出现问题

### ISSUE THREAD

**Issue by abshawn** [buzheng/start-project-easyui-springmvc-mybatis#1]
环境：myeclipse10+maven+tomcat7+jdk1.7
进行编译发布后：出现如下问题：
console：
六月 01, 2016 9:18:18 上午 org.apache.catalina.startup.ContextConfig processServletContainerInitializers
SEVERE: Failed to detect ServletContainerInitializers for context with name [/start-project-easyui-springmvc-mybatis]
java.io.IOException: java.lang.ClassNotFoundException: org.springframework.web.SpringServletContainerInitializer
	at org.apache.catalina.startup.WebappServiceLoader.loadServices(WebappServiceLoader.java:199)
	at org.apache.catalina.startup.WebappServiceLoader.load(WebappServiceLoader.java:157)
	at org.apache.catalina.startup.ContextConfig.processServletContainerInitializers(ContextConfig.java:1575)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1281)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:889)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:386)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5479)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1574)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1564)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.ClassNotFoundException: org.springframework.web.SpringServletContainerInitializer
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1856)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1705)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.catalina.startup.WebappServiceLoader.loadServices(WebappServiceLoader.java:196)
	... 16 more
六月 01, 2016 9:18:18 上午 org.apache.catalina.startup.ContextConfig configureStart
SEVERE: Marking this application unavailable due to previous error(s)

请看哪里出了问题？？

**Comment by abshawn** [comment]
这个问题已解决了，maven已经提供了jar吧，不用将jar复制到web-inf/bin/ 中。
这样折腾一下就解决了

**Comment by buzheng** [comment]
maven 项目所有的依赖在 pom.xml 定义了， 自己不用管 jar 的。你导入eclipse 的时候，选择导入 exists maven project

**Comment by buzheng** [comment]
估计是里面有oracle的依赖，你本地没有。 你需要换成你自己的数据库驱动，一般你都用的 mysql 吧。

**Comment by abshawn** [comment]
我用的就是 oracle 数据库驱动
